/**
 * MissionGrammar.ts
 *
 * Pillar: The Four-Fold Shield (Clean Architecture) - Domain Entities
 * Pillar: The Storyteller’s Code (Literate Documentation)
 *
 * Intent:
 * Defines the formal grammar for generative missions.
 * Instead of hard-coded logic, missions are described as a sequence of rules
 * and transitions that the GenericMissionStrategy interprets.
 *
 * Design Pattern: Strategy / State
 * Why: To allow for infinite mission permutations without increasing code complexity.
 */

import { GameEventType } from '../../services/SimulationBus';

/**
 * A predicate that determines if a GameEvent satisfies a mission step.
 */
export interface CommandMatcher {
    /**
     * The type of simulation event to match against.
     */
    type: GameEventType;
    
    /**
     * Optional regex or string match for the primary target of the event 
     * (e.g., command name, register name, or file path).
     */
    target?: string;
    
    /**
     * Optional regex or string match for the result or payload value 
     * (e.g., command output, new register value).
     */
    expectedValue?: string | number;
    
    /**
     * Optional key for a pre-defined complex logic rule (e.g., 'FILE_CONTAINS_SECRET').
     */
    ruleKey?: string;
}

/**
 * Defines the logic for a single discrete step in a mission.
 */
export interface StepRule {
    /**
     * Unique identifier for this step within the mission.
     */
    id: string;
    
    /**
     * Semantic category of the task (informative for UI/Tutor).
     */
    stepType: 'CONNECT' | 'LOCATE' | 'MODIFY' | 'RUN_SCHEME' | 'RUN_RISCV' | 'GENERIC';
    
    /**
     * Human-readable objective for this specific step.
     */
    description: string;

    /**
     * The semantic intent for the Tutor to proactively describe this step.
     */
    tutorIntent?: string;
    
    /**
     * Optional regex for the required current working directory to validate this step.
     */
    cwdPattern?: string;
    
    /**
     * Optional text for the typing tutor lesson associated with this step.
     */
    lessonText?: string;
    
    /**
     * The predicate that must be satisfied to complete this step.
     */
    commandMatcher: CommandMatcher;
    
    /**
     * What happens once this step is satisfied.
     */
    onComplete?: StepTransition;
}

/**
 * Defines the transition to the next state of the mission.
 */
export interface StepTransition {
    /**
     * The ID of the next step to activate. If omitted, the mission may complete.
     */
    nextStepId?: string;
    
    /**
     * Optional ID of a tutorial lesson to trigger upon completion of this step.
     */
    startLessonId?: string;
    
    /**
     * The semantic intent for the Tutor (e.g., 'CELEBRATE_SUCCESS', 'NUDGE_NEXT').
     */
    tutorIntent?: string;
    
    /**
     * Optional override for the Tutor's tone profile for this specific transition.
     */
    tutorToneProfile?: string;
}

/**
 * The top-level definition of a mission archetype's grammar.
 * This structure is data-driven and can be generated by Scheme macros or TS factories.
 */
export interface MissionGrammar {
    /**
     * The semantic archetype (e.g., 'breach', 'exfiltrate', 'sabotage').
     */
    archetype: string;
    
    /**
     * The set of rules defining the mission's progression.
     */
    steps: StepRule[];
    
    /**
     * The entry point of the mission.
     */
    initialStepId: string;
}
