/**
 * AwkInterpreter - Domain Command
 *
 * Interprets the AST generated by the Parser.
 *
 * Pillar: The Four-Fold Shield (Strict Architecture)
 * Pillar: Pragmatic Design Patterns (Visitor)
 *
 * Refactor:
 * Delegates execution to `AwkExecutionVisitor`.
 * Delegates state to `AwkRuntimeEnvironment`.
 */

import { ProgramNode } from './AwkParser';
import { AwkRuntimeEnvironment } from './AwkRuntimeEnvironment';
import { AwkExecutionVisitor } from './AwkExecutionVisitor';

export class AwkInterpreter {

    /**
     * Executes the Awk program against the input string.
     * @param ast The parsed ProgramNode.
     * @param input Full input text (stdin/file content).
     * @returns The STDOUT as a string.
     */
    public execute(ast: ProgramNode, input: string): string {
        const env = new AwkRuntimeEnvironment();
        const visitor = new AwkExecutionVisitor(env);

        // 1. BEGIN blocks
        for (const block of ast.beginBlocks) {
            visitor.visit(block);
        }

        // 2. Main Loop
        if (input.length > 0) {
            const lines = input.split('\n');
            for (const line of lines) {
                env.updateFields(line); // Updates NR, NF, $0, $1...

                for (const pa of ast.patternActions) {
                    visitor.visit(pa);
                }
            }
        } else if (ast.patternActions.length > 0) {
            // Even with empty input, if we have pattern actions?
            // Usually awk requires input stream or BEGIN/END.
            // If input is empty string, split might return [""] (1 line) or []?
            // "abc".split("d") -> ["abc"]. "".split("d") -> [""]
            // If input is truly empty, we loop 0 times?
            // "If input is empty... BEGIN and END are executed."
        }

        // 3. END blocks
        for (const block of ast.endBlocks) {
            visitor.visit(block);
        }

        return visitor.getOutput();
    }
}
