/**
 * POSIX shell conformance cases.
 *
 * Each script runs both in the simulator and (when regenerating goldens)
 * in a real POSIX shell (dash) inside an empty scratch directory. Scripts
 * must only touch relative paths so both environments behave the same.
 */
export const SHELL_CASES: { name: string; script: string }[] = [
    // --- Quoting (XCU 2.2) ---
    { name: 'quote/single', script: `echo 'a  b' 'c"d' 'e\\f'` },
    { name: 'quote/double', script: `x=val; echo "x=$x" "\\$x" "a\\"b" "back\\\\slash" "keep\\q"` },
    { name: 'quote/backslash', script: `echo a\\ b \\$HOME \\\\` },
    { name: 'quote/mixed', script: `echo "a"'b'c"d e"` },
    { name: 'quote/empty-args', script: `set -- "" '' x; echo $#` },
    { name: 'quote/line-continuation', script: 'echo a\\\nb' },
    { name: 'quote/dq-newline', script: 'echo "line1\nline2"' },
    { name: 'quote/hash-not-comment', script: `echo a#b '#c' "#d" # real comment` },

    // --- Parameters & variables (2.5, 2.6.2) ---
    { name: 'param/assign', script: `a=1 b=2; echo $a$b` },
    { name: 'param/braces', script: `v=foo; echo \${v}bar $vbar.` },
    { name: 'param/default', script: `unset u; e=; echo \${u-d1} \${u:-d2} [\${e-d3}] \${e:-d4}` },
    { name: 'param/assign-default', script: `unset u; echo \${u=set1}; echo $u; e=; echo \${e:=set2}; echo $e` },
    { name: 'param/alternative', script: `s=x; e=; unset u; echo [\${s+alt}] [\${e+alt}] [\${e:+alt}] [\${u+alt}]` },
    { name: 'param/error', script: `unset u; (echo \${u?missing}) 2>/dev/null; echo status=$?` },
    { name: 'param/length', script: `s=hello; echo \${#s}; set -- a b c; echo \${#}` },
    { name: 'param/prefix-suffix', script: `p=/usr/local/lib/libfoo.so.1; echo \${p#*/} \${p##*/} \${p%.*} \${p%%.*}` },
    { name: 'param/pattern-quoted', script: `x='a*b*c'; echo "\${x#*'*'}" \${x%"*c"}` },
    { name: 'param/special', script: `set -- one two three; echo $# $1 $3 "$*"; false; echo $?; true; echo $?` },
    { name: 'param/positional-10', script: `set -- 1 2 3 4 5 6 7 8 9 ten; echo \${10} $10` },
    { name: 'param/at-quoted', script: `set -- "a b" c; for i in "$@"; do echo "<$i>"; done; for i in $@; do echo "[$i]"; done` },
    { name: 'param/star-ifs', script: `set -- a b c; IFS=:; echo "$*"; IFS=; echo "$*"` },
    { name: 'param/at-empty', script: `set --; for i in "$@"; do echo never; done; echo "n=$#"; set -- "$@"; echo $#` },
    { name: 'param/nounset', script: `set -u; (echo $nosuchvar) 2>/dev/null; echo st=$?` },
    { name: 'param/dollar-dollar', script: `[ "$$" -gt 0 ] && echo pid-ok` },

    // --- Command substitution (2.6.3) ---
    { name: 'cmdsub/basic', script: `echo "[$(echo hi)]" [\`echo bq\`]` },
    { name: 'cmdsub/nested', script: `echo $(echo $(echo deep))` },
    { name: 'cmdsub/trailing-newlines', script: `x=$(printf 'a\\n\\n\\n'); echo "[$x]"` },
    { name: 'cmdsub/status', script: `x=$(false); echo $?; y=$(exit 3); echo $?` },
    { name: 'cmdsub/quotes-inside', script: `echo "$(echo "inner quoted")"` },
    { name: 'cmdsub/parens', script: `echo $( (echo sub) )` },
    { name: 'cmdsub/case-inside', script: `x=$(case a in a) echo A;; esac); echo $x` },
    { name: 'cmdsub/no-split-in-dq', script: `x="$(echo 'a   b')"; echo "$x"; echo $(echo 'a   b')` },

    // --- Arithmetic (2.6.4) ---
    { name: 'arith/basic', script: `echo $((1+2*3)) $(( (1+2)*3 )) $((7/2)) $((7%3)) $((-7/2))` },
    { name: 'arith/vars', script: `a=5 b=3; echo $((a*b)) $(($a+$b)) $((a-=1)) $a` },
    { name: 'arith/compare-logic', script: `echo $((3>2)) $((3<2)) $((1&&0)) $((1||0)) $((!5)) $((2==2))` },
    { name: 'arith/bits', script: `echo $((5&3)) $((5|3)) $((5^3)) $((1<<4)) $((256>>2)) $((~0))` },
    { name: 'arith/ternary', script: `x=4; echo $((x>3 ? 10 : 20))` },
    { name: 'arith/bases', script: `echo $((0x1f)) $((010)) $((0))` },
    { name: 'arith/assign-ops', script: `i=1; : $((i+=2)) $((i*=5)); echo $i` },
    { name: 'arith/var-number', script: `a=21; echo $((a*2)) $((a))` },
    { name: 'arith/div-zero', script: `(echo $((1/0))) 2>/dev/null; echo st=$?` },

    // --- Field splitting (2.6.5) ---
    { name: 'split/default', script: `x='  a  b   c  '; set -- $x; echo $# "$1" "$3"` },
    { name: 'split/custom-ifs', script: `IFS=:; x='a::b:c'; set -- $x; echo $#; for i in $x; do echo "[$i]"; done` },
    { name: 'split/mixed-ifs', script: `IFS=' :'; x=' a : b:c '; set -- $x; echo $#: "$1" "$2" "$3"` },
    { name: 'split/no-split-literal', script: `IFS=:; echo a:b c:d` },
    { name: 'split/empty-ifs', script: `IFS=; x='a b'; set -- $x; echo $#` },
    { name: 'split/empty-expansion-removed', script: `e=; set -- $e x $e; echo $#` },

    // --- Pathname expansion (2.6.6, 2.13) ---
    { name: 'glob/star', script: `touch b.txt a.txt c.log; echo *.txt; echo *.none` },
    { name: 'glob/question-bracket', script: `touch f1 f2 f3 fa; echo f?; echo f[12]; echo f[!0-9]` },
    { name: 'glob/quoted', script: `touch x1 x2; echo "x*" 'x?' x\\*` },
    { name: 'glob/hidden', script: `touch .hidden visible; echo *; echo .h*` },
    { name: 'glob/dirs', script: `mkdir -p d1/s d2/s; touch d1/s/f; echo d*/s; echo */s/*` },
    { name: 'glob/noglob', script: `touch g1; set -f; echo g*; set +f; echo g*` },
    { name: 'glob/class', script: `touch A1 b2 C3; echo [[:upper:]]*` },

    // --- Tilde ---
    { name: 'tilde/home', script: `HOME=/myhome; echo ~ ~/x "~" x~` },
    { name: 'tilde/assign', script: `HOME=/h; p=~/bin:~/lib; echo $p` },

    // --- Redirection (2.7) ---
    { name: 'redir/out-append', script: `echo one > f; echo two >> f; cat f` },
    { name: 'redir/no-space', script: `echo a>f;cat<f` },
    { name: 'redir/input', script: `printf 'x\\ny\\n' > in; tr x z < in` },
    { name: 'redir/stderr-null', script: `ls nonexistent 2>/dev/null; echo st=$?` },
    { name: 'redir/stderr-to-stdout', script: `{ echo out; echo err >&2; } 2>&1 | tr a-z A-Z` },
    { name: 'redir/order', script: `{ echo e >&2; } 2>&1 >/dev/null | cat` },
    { name: 'redir/fd3', script: `exec 3>/dev/null; echo visible; { echo hidden >&3; } 3>f3; cat f3` },
    { name: 'redir/close', script: `(echo x >&-) 2>/dev/null; echo st=$?` },
    { name: 'redir/clobber', script: `echo 1 > c; set -C; (echo 2 > c) 2>/dev/null; echo st=$?; echo 3 >| c; cat c` },
    { name: 'redir/compound', script: `for i in 1 2; do echo $i; done > loop.out; cat loop.out` },
    { name: 'redir/while-read', script: `printf 'l1\\nl2\\nl3\\n' > lines; while read l; do echo "<$l>"; done < lines` },
    { name: 'redir/missing-input', script: `cat < nofile 2>/dev/null; echo st=$?` },
    { name: 'redir/empty-create', script: `> created; ls created` },
    { name: 'redir/dev-null-read', script: `cat < /dev/null; echo done` },

    // --- Here-documents (2.7.4) ---
    { name: 'heredoc/expand', script: 'v=world\ncat <<EOF\nhello $v\n$(echo sub) $((1+1))\nEOF' },
    { name: 'heredoc/quoted', script: "v=world\ncat <<'EOF'\nhello $v\n`not run`\nEOF" },
    { name: 'heredoc/dash', script: 'cat <<-END\n\tindented\n\t\tdouble\n\tEND' },
    { name: 'heredoc/two', script: 'cat <<A; cat <<B\nfirst\nA\nsecond\nB' },
    { name: 'heredoc/backslash', script: 'cat <<EOF\na\\$b \\\\ c\\\nd\nEOF' },
    { name: 'heredoc/pipe', script: 'cat <<EOF | tr a-z A-Z\nshout\nEOF' },

    // --- Pipelines & lists (2.9.2, 2.9.3) ---
    { name: 'pipe/basic', script: `printf 'b\\na\\nc\\n' | sort | head -n 2` },
    { name: 'pipe/status', script: `false | true; echo $?; true | false; echo $?` },
    { name: 'pipe/negate', script: `! true; echo $?; ! false; echo $?; ! false | false; echo $?` },
    { name: 'pipe/subshell-vars', script: `x=1; echo | x=2; echo $x` },
    { name: 'list/and-or', script: `true && echo a; false && echo b; false || echo c; true || echo d; false && echo e || echo f` },
    { name: 'list/newline-after-op', script: 'true &&\necho joined ||\necho never' },
    { name: 'list/async', script: `echo bg > bgout & wait; cat bgout` },
    { name: 'list/semicolons', script: `echo 1; echo 2;echo 3` },

    // --- Compound commands (2.9.4) ---
    { name: 'group/brace', script: `{ echo a; echo b; } | wc -l | tr -d ' '` },
    { name: 'group/subshell-isolation', script: `x=outer; (x=inner; echo $x); echo $x; (cd /; pwd) >/dev/null; echo kept` },
    { name: 'group/subshell-exit', script: `(exit 7); echo $?` },
    { name: 'if/basic', script: `if true; then echo yes; else echo no; fi; if false; then echo yes; elif true; then echo elif; fi` },
    { name: 'if/status', script: `if false; then :; fi; echo $?` },
    { name: 'if/nested', script: `x=2; if [ $x -gt 1 ]; then if [ $x -lt 3 ]; then echo mid; fi; fi` },
    { name: 'for/basic', script: `for i in a b c; do printf %s $i; done; echo` },
    { name: 'for/positional', script: `set -- p q; for i; do echo $i; done` },
    { name: 'for/glob', script: `touch m1 m2; for f in m*; do echo $f; done` },
    { name: 'for/empty', script: `for i in; do echo never; done; echo after` },
    { name: 'for/newline-syntax', script: 'for i in 1 2\ndo\n  echo $i\ndone' },
    { name: 'while/count', script: `i=0; while [ $i -lt 5 ]; do i=$((i+1)); done; echo $i` },
    { name: 'until/count', script: `i=0; until [ $i -ge 3 ]; do echo $i; i=$((i+1)); done` },
    { name: 'loop/break-continue', script: `for i in 1 2 3 4 5; do [ $i = 2 ] && continue; [ $i = 4 ] && break; echo $i; done` },
    { name: 'loop/break-n', script: `for i in 1 2; do for j in a b; do echo $i$j; break 2; done; done; echo out` },
    { name: 'loop/continue-n', script: `for i in 1 2; do for j in a b; do echo $i$j; continue 2; done; echo never; done` },
    { name: 'loop/status', script: `for i in 1; do false; done; echo $?` },
    { name: 'case/basic', script: `for w in apple banana cherry 42; do case $w in a*) echo A;; b*|c*) echo BC;; [0-9]*) echo N;; esac; done` },
    { name: 'case/default-none', script: `case zzz in a) echo a;; esac; echo st=$?` },
    { name: 'case/paren-pattern', script: `case x in (x) echo paren;; esac` },
    { name: 'case/quoted-pattern', script: `p='*'; case abc in "$p") echo literal;; $p) echo glob;; esac` },
    { name: 'case/last-no-dsemi', script: `case b in a) echo a;; b) echo b; esac` },
    { name: 'case/multiline', script: 'case "$1" in\n  "")\n    echo empty\n    ;;\n  *) echo other ;;\nesac' },
    { name: 'case/empty-body', script: `case a in a) ;; esac; echo ok` },

    // --- Functions (2.9.5) ---
    { name: 'func/args', script: `f() { echo "$# $1 $2"; }; f x y; echo "$#"` },
    { name: 'func/return', script: `f() { return 3; echo never; }; f; echo $?` },
    { name: 'func/globals', script: `f() { g=set; }; f; echo $g` },
    { name: 'func/recursion', script: `fact() { if [ $1 -le 1 ]; then echo 1; else echo $(( $1 * $(fact $(($1-1))) )); fi; }; fact 6` },
    { name: 'func/redirect', script: `f() { echo inside; } > fout; f; cat fout` },
    { name: 'func/positional-restore', script: `set -- outer; f() { set -- inner; echo $1; }; f; echo $1` },
    { name: 'func/local', script: `x=global; f() { local x=local; echo $x; }; f; echo $x` },
    { name: 'func/override-builtin', script: `echo() { printf 'wrapped:%s\\n' "$*"; }; echo hi; command echo direct` },

    // --- Builtins (2.14) ---
    { name: 'builtin/colon', script: `: ignored args; echo $?` },
    { name: 'builtin/eval', script: `cmd='echo evaluated'; eval $cmd; eval 'x=1; y=2'; echo $x$y` },
    { name: 'builtin/eval-quotes', script: `eval "echo \\"a  b\\""` },
    { name: 'builtin/dot', script: `echo 'sourced=yes; echo in-file' > lib.sh; . ./lib.sh; echo $sourced` },
    { name: 'builtin/export', script: `export A=1; B=2; sh -c 'echo "[$A][$B]"'` },
    { name: 'builtin/export-prefix', script: `V=temp sh -c 'echo $V'; echo "[$V]"` },
    { name: 'builtin/readonly', script: `readonly R=1; (R=2) 2>/dev/null; echo st=$? R=$R` },
    { name: 'builtin/unset', script: `x=1; unset x; echo "[\${x-unset}]"; f() { :; }; unset -f f; (f) 2>/dev/null; echo st=$?` },
    { name: 'builtin/shift', script: `set -- a b c d; shift; echo $*; shift 2; echo $*; (shift 5) 2>/dev/null; echo st=$?` },
    { name: 'builtin/set-options', script: `set -e; echo "$-" | grep -q e && echo errexit-on; set +e; echo "$-" | grep -q e || echo errexit-off` },
    { name: 'builtin/set-e', script: `(set -e; echo before; false; echo after); echo st=$?` },
    { name: 'builtin/set-e-tested', script: `set -e; if false; then :; fi; false || true; ! true; false && true; echo survived` },
    { name: 'builtin/set-x', script: `(set -x; echo traced) 2>&1` },
    { name: 'builtin/trap-exit', script: `(trap 'echo cleanup' EXIT; echo body)` },
    { name: 'builtin/trap-exit-sh', script: `sh -c 'trap "echo bye" 0; echo hi; exit 4'; echo $?` },
    { name: 'builtin/read-fields', script: `echo 'one two three four' | { read a b c; echo "$a|$b|$c"; }` },
    { name: 'builtin/read-ifs', script: `echo 'a:b:c' | { IFS=: read x y; echo "$x|$y"; }` },
    { name: 'builtin/read-raw', script: `printf 'a\\\\b\\n' | { read -r x; echo "$x"; }; printf 'a\\\\b\\n' | { read x; echo "$x"; }` },
    { name: 'builtin/read-eof', script: `printf 'partial' | { read x; echo "st=$? x=$x"; }` },
    { name: 'builtin/getopts', script: `set -- -a -b val -c rest; while getopts ab:c o; do echo "$o \${OPTARG-}"; done; shift $((OPTIND-1)); echo "rest=$*"` },
    { name: 'builtin/getopts-cluster', script: `set -- -xy -zarg; while getopts xyz: o; do echo "$o \${OPTARG-}"; done` },
    { name: 'builtin/command-v', script: `command -v cd; command -v nosuchcmd || echo missing; f() { :; }; command -v f` },
    { name: 'builtin/type', script: `type cd; type if; f() { :; }; type f >/dev/null && echo fn` },
    { name: 'builtin/alias', script: 'alias greet="echo hello"\ngreet world\nunalias greet\ngreet 2>/dev/null || echo gone' },
    { name: 'builtin/cd', script: `mkdir -p sub/dir; cd sub/dir; basename "$(pwd)"; cd ..; basename "$PWD"; cd -  >/dev/null; basename "$PWD"` },
    { name: 'builtin/cd-errors', script: `cd nowhere 2>/dev/null; echo st=$?; touch file; cd file 2>/dev/null; echo st=$?` },
    { name: 'builtin/exit-code', script: `sh -c 'exit 42'; echo $?; sh -c 'false'; echo $?` },
    { name: 'builtin/sh-args', script: `sh -c 'echo "$0 $1 $2 $#"' name a b` },
    { name: 'builtin/exec', script: `sh -c 'exec echo replaced; echo never'` },
    { name: 'builtin/true-false', script: `true; echo $?; false; echo $?` },

    // --- Scripts & command search (2.9.1) ---
    { name: 'script/run', script: `printf '#!/bin/sh\\necho "script $1"\\nexit 5\\n' > s.sh; chmod +x s.sh; ./s.sh arg; echo st=$?` },
    { name: 'script/no-exec-bit', script: `echo 'echo hi' > ne.sh; ./ne.sh 2>/dev/null; echo st=$?; sh ne.sh` },
    { name: 'script/not-found', script: `nosuchcommand_xyz 2>/dev/null; echo st=$?; ./missing 2>/dev/null; echo st=$?` },
    { name: 'script/vars-isolated', script: `echo 'inner=1' > v.sh; sh v.sh; echo "[\${inner-}]"` },
    { name: 'script/path-search', script: `mkdir -p mybin; printf '#!/bin/sh\\necho from-path\\n' > mybin/mytool; chmod 755 mybin/mytool; PATH="$PWD/mybin:$PATH"; mytool` },

    // --- Utilities commonly used in scripts ---
    { name: 'util/test', script: `[ 1 -eq 1 ] && echo eq; [ a = b ] || echo ne; [ -z "" ] && echo z; [ -n x ] && echo n; test 3 -gt 2 && echo gt` },
    { name: 'util/test-files', script: `touch tf; mkdir td; [ -f tf ] && echo f; [ -d td ] && echo d; [ -e nope ] || echo noexist; [ -s tf ] || echo empty` },
    { name: 'util/printf', script: `printf '%s-%d-%05.1f|%x|%o|%c|%%\\n' str 42 3.14159 255 8 char` },
    { name: 'util/printf-reuse', script: `printf '%s=%s\\n' a 1 b 2 c` },
    { name: 'util/expr', script: `expr 2 + 3; expr 10 / 3; expr length hello` },
    { name: 'util/wc', script: `printf 'a b\\nc\\n' > w; wc -l < w; wc -w < w; wc -c < w` },
    { name: 'util/cut', script: `echo 'a:b:c' | cut -d: -f2; echo hello | cut -c2-4` },
    { name: 'util/sort-uniq', script: `printf 'b\\na\\nb\\nc\\na\\n' | sort | uniq -c | tr -s ' '` },
    { name: 'util/head-tail', script: `printf '1\\n2\\n3\\n4\\n5\\n' > n; head -n 2 n; tail -n 2 n` },
    { name: 'util/grep', script: `printf 'apple\\nbanana\\ncherry\\n' > g; grep an g; grep -c a g; grep -v a g; grep -q zzz g || echo nomatch` },
    { name: 'util/sed', script: `echo 'hello world' | sed 's/world/there/'; printf 'a\\nb\\nc\\n' | sed -n 2p` },
    { name: 'util/awk', script: `printf '1 2\\n3 4\\n' | awk '{ s += $1 * $2 } END { print s }'` },
    { name: 'util/tr', script: `echo hello | tr a-z A-Z; echo 'a  b' | tr -s ' '; echo abc | tr -d b` },
    { name: 'util/basename-dirname', script: `basename /a/b/c.txt; basename /a/b/c.txt .txt; dirname /a/b/c.txt; dirname c` },
    { name: 'util/cat-n', script: `printf 'x\\ny\\n' | cat -` },
    { name: 'util/tee', script: `echo teed | tee tee.out; cat tee.out` },
    { name: 'util/xargs', script: `printf 'a\\nb\\n' | xargs echo items:` },
    { name: 'util/mkdir-rm', script: `mkdir -p x/y/z; [ -d x/y/z ] && echo made; rm -r x; [ -e x ] || echo removed` },
    { name: 'util/ls', script: `mkdir lsd; touch lsd/b lsd/a; ls lsd` },
];
