/**
 * Utility conformance cases, differential against the host's GNU/POSIX tools.
 * Scripts must stay inside the scratch directory (relative paths only).
 */
import { DifferentialCase } from './differential';

const SAMPLE = `printf 'hello\\tworld\\n\\001\\377ABC' > s; `;
const REPEAT = `printf 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' > r; `;

/** awk: the host awk is mawk, so only behaviour common to POSIX awks is compared. */
const AWK_DATA = `printf 'alice 30 NY\\nbob 25 LA\\ncarol 35 NY\\ndave 40 SF\\n' > d; `;
const AWK_CASES: DifferentialCase[] = [
    { name: 'awk/fields', script: `${AWK_DATA}awk '{print $1, $NF; print NF, $(NF-1)}' d` },
    { name: 'awk/sum', script: `${AWK_DATA}awk '{s += $2} END {print s, s/NR, NR}' d` },
    { name: 'awk/patterns', script: `${AWK_DATA}awk '/NY/' d; awk '$2 > 30 {print $1}' d; awk '!/NY/ && $2 < 30' d` },
    { name: 'awk/range', script: `seq 1 10 | awk 'NR==3, NR==5'; seq 1 10 | awk '/7/,/7/ {print "r", $0}'; seq 1 6 | awk '$0==2, $0==99'` },
    { name: 'awk/begin-end', script: `: > empty; awk 'BEGIN {print "b"} END {print "e", NR}' empty; awk 'BEGIN {x = 1; print x}'; echo st=$?` },
    { name: 'awk/default-fs', script: `printf '  a   b\\tc  \\n\\n x\\n' | awk '{print NF ":" $1 ":" $2 ":" $3}'` },
    { name: 'awk/fs-char', script: `printf 'a:b::c\\n:x:\\n' | awk -F: '{print NF; for (i = 1; i <= NF; i++) printf "[%s]", $i; print ""}'` },
    { name: 'awk/fs-tab', script: `printf 'a b\\tc\\td e\\n' | awk -F '\\t' '{print $2 "|" NF}'; printf 'a b\\tc\\n' | awk 'BEGIN {FS = "\\t"} {print $1}'` },
    { name: 'awk/fs-regex', script: `printf 'a1b22c333d\\n' | awk -F '[0-9]+' '{print NF, $1, $4}'; printf 'x, y,z\\n' | awk 'BEGIN {FS = ", *"} {print $2 $3}'` },
    { name: 'awk/fs-pipe', script: `echo 'a|b|c' | awk -F'|' '{print $2}'; echo 'a.b.c' | awk -F. '{print $3}'` },
    { name: 'awk/ofs-ors', script: `${AWK_DATA}awk 'BEGIN {OFS = "-"; ORS = ";"} {print $1, $2} END {printf "\\n"}' d` },
    { name: 'awk/field-assign', script: `echo 'a b c' | awk '{$2 = "X"; print; print NF}'; echo 'a b c' | awk '{$5 = "e"; print; print NF}'; echo 'a b c' | awk 'BEGIN {OFS = ":"} {$1 = $1; print}'` },
    { name: 'awk/nf-assign', script: `echo 'a b c d' | awk '{NF = 2; print; print NF}'; echo 'a b' | awk 'BEGIN {OFS = ","} {NF = 4; print}'` },
    { name: 'awk/record-assign', script: `echo 'a b' | awk '{$0 = "x y z"; print NF, $3}'; echo 'a b' | awk '{$3 = ""; print NF; print}'` },
    { name: 'awk/rs-char', script: `printf 'a,b,c' | awk 'BEGIN {RS = ","} {print NR ": " $0}'; printf 'x;y;' | awk -v RS=';' '{print}'` },
    { name: 'awk/rs-paragraph', script: `printf '\\n\\na b\\nc\\n\\n\\nd e f\\n\\n' | awk 'BEGIN {RS = ""} {print NR, NF, $1, $NF}'` },
    { name: 'awk/no-trailing-newline', script: `printf 'a\\nb' | awk '{print NR, $0}'; printf '' | awk 'END {print NR}'` },
    { name: 'awk/arith', script: `awk 'BEGIN {print 1+2*3, (1+2)*3, 7/2, 7%3, -7%3, 2^10, 2^3^2, -2^2, 10-2-3, 1e3, .5 + .25}'` },
    { name: 'awk/ofmt-convfmt', script: `awk 'BEGIN {print 0.1+0.2, 1/3, 100000*3, 1e6, 3.0; OFMT = "%.2f"; print 3.14159; x = 3.14159 ""; print x; CONVFMT = "%.3f"; y = 3.14159 ""; print y; print 17 ""}'` },
    { name: 'awk/integers', script: `awk 'BEGIN {print 2^31, 2^40, 1000000 * 1000000, int(-3.7), int(3.7), int("12abc")}'` },
    { name: 'awk/assign-ops', script: `awk 'BEGIN {x = 10; x += 5; print x; x -= 3; print x; x *= 2; print x; x /= 4; print x; x %= 4; print x; x ^= 3; print x; a = b = 7; print a, b}'` },
    { name: 'awk/incdec', script: `awk 'BEGIN {i = 5; print i++, i, ++i, i--, --i, i; a[1]++; a[1]++; print a[1]; $0 = "3 4"; $1++; print}'` },
    { name: 'awk/unary', script: `awk 'BEGIN {x = "3x"; print -x, +x, !x, !0, !"", !"a", - -4}'` },
    { name: 'awk/ternary', script: `seq 1 5 | awk '{print ($1 % 2 ? "odd" : "even"), ($1 > 3 ? "big" : $1 > 1 ? "mid" : "small")}'` },
    { name: 'awk/logic', script: `awk 'BEGIN {print (1 && 0), (1 || 0), (0 || ""), ("a" && "0"), (x || y)}'` },
    { name: 'awk/concat', script: `awk 'BEGIN {x = "a" "b" 1 + 2; print x; print 1 " " 2, 3 4; print -1 " " -2}'` },
    { name: 'awk/compare-strnum', script: `printf '10 9\\n10 10.0\\nabc 10\\n1e1 10\\n 2 2\\n' | awk '{print ($1 < $2), ($1 == $2)}'` },
    { name: 'awk/compare-rules', script: `awk 'BEGIN {print ("10" < "9"), (10 < 9), ("a" < "b"), ("abc" < "abd"), (2 < "10"), (x == 0), (x == "")}'; echo 10 | awk '{x = $1; print (x < 9), (x "" < 9)}'` },
    { name: 'awk/uninit', script: `awk 'BEGIN {print length(x), x + 0, "[" x "]"; if (!(1 in arr)) print "absent"; arr[1]; if (1 in arr) print "created"}'` },
    { name: 'awk/regex-match', script: `awk 'BEGIN {print ("abc" ~ /b/), ("abc" ~ "^b"), ("abc" !~ /z/), ("a.c" ~ /a\\.c/), ("abc" ~ "a.c"); re = "^[0-9]+$"; print ("123" ~ re), ("12a" ~ re)}'` },
    { name: 'awk/regex-ere', script: `printf 'color\\ncolour\\ncolouur\\nabab\\nx+y\\n' | awk '/colou?r$/ {print "1", $0} /^(ab)+$/ {print "2", $0} /x\\+y/ {print "3", $0} /[[:digit:]]/ {print "4"}'` },
    { name: 'awk/regex-brackets', script: `printf 'a/b\\na]b\\nA-b\\n' | awk '/a\\/b/ {print "slash"} /[]]/ {print "bracket"} /^[[:upper:]]-/ {print "class"}'` },
    { name: 'awk/dynamic-regex', script: `printf 'a.b\\naxb\\n' | awk -v pat='a\\\\.b' '$0 ~ pat'; printf 'foo\\nbar\\n' | awk -v p=o '$0 ~ p "o"'` },
    { name: 'awk/if-else', script: `seq 1 4 | awk '{ if ($1 == 1) print "one"; else if ($1 == 2) { print "two" } else print "many" }'` },
    { name: 'awk/loops', script: `awk 'BEGIN {for (i = 0; i < 3; i++) printf "%d ", i; print ""; i = 0; while (i < 3) {i++; if (i == 2) continue; printf "w%d ", i}; print ""; do {j++} while (j < 5); print j; for (;;) {k++; if (k > 3) break}; print k}'` },
    { name: 'awk/for-in', script: `${AWK_DATA}awk '{c[$3]++} END {for (k in c) print k, c[k]}' d | sort` },
    { name: 'awk/delete', script: `awk 'BEGIN {a[1]; a[2]; a[3]; delete a[2]; n = 0; for (k in a) n++; print n, (2 in a); split("", a); for (k in a) n++; print n}'` },
    { name: 'awk/multi-subscript', script: `awk 'BEGIN {a[1, 2] = 3; for (k in a) {split(k, p, SUBSEP); print p[1], p[2]}; print ((1, 2) in a), ((2, 1) in a)}'` },
    { name: 'awk/next', script: `seq 1 6 | awk 'NR % 2 == 0 {next} {print}'` },
    { name: 'awk/exit', script: `seq 1 5 | awk '{print} NR == 2 {exit 3} END {print "end"}'; echo st=$?; awk 'BEGIN {exit} END {print "e"}'; echo st=$?; seq 1 3 | awk 'END {exit 4}'; echo st=$?` },
    { name: 'awk/exit-in-end', script: `echo x | awk '{exit 5} END {print "end"; exit}'; echo st=$?` },
    { name: 'awk/functions', script: `awk 'function fact(n) {return n <= 1 ? 1 : n * fact(n - 1)} function noret() {} BEGIN {print fact(5), fact(10); x = noret(); print "[" x "]"}'` },
    { name: 'awk/func-locals', script: `awk 'function f(a, b,   tmp) {tmp = a + b; g = tmp; return tmp * 2} BEGIN {tmp = "keep"; print f(1, 2), tmp, g}'` },
    { name: 'awk/func-arrays', script: `awk 'function fill(arr, n,  i) {for (i = 1; i <= n; i++) arr[i] = i * i} function sum(arr,  k, s) {for (k in arr) s += arr[k]; return s} BEGIN {fill(sq, 4); print sum(sq), sq[3]}'` },
    { name: 'awk/func-scalar-byvalue', script: `awk 'function f(x) {x = 99; return x} BEGIN {y = 1; f(y); print y}'` },
    { name: 'awk/length', script: `echo 'hello world' | awk '{print length, length(), length($1), length(12345)}'; awk 'BEGIN {a[1]; a[2]; print length(a)}'` },
    { name: 'awk/substr', script: `awk 'BEGIN {s = "hello"; print substr(s, 2, 3) "|" substr(s, 2) "|" substr(s, 1, 2) "|" substr(s, 4, 100) "|" substr(s, 9) "|" substr(s, 2, -1) "|"}'` },
    { name: 'awk/index', script: `awk 'BEGIN {print index("hello", "l"), index("hello", "lo"), index("hello", "z")}'` },
    { name: 'awk/split', script: `awk 'BEGIN {n = split("a b  c", a); print n, a[1], a[3]; n = split("a:b:c", b, ":"); print n, b[2]; n = split("a1b22c", c, /[0-9]+/); print n, c[3]; n = split("", d); print n; n = split("  x  ", e); print n, e[1]}'` },
    { name: 'awk/split-strnum', script: `awk 'BEGIN {split("10 9", a); print (a[1] > a[2])}'` },
    { name: 'awk/sub-gsub', script: `awk 'BEGIN {s = "aaa"; n = gsub(/a/, "b", s); print n, s; s = "hello"; sub(/l/, "L", s); print s; s = "abc"; gsub(/x*/, "-", s); print s; s = "foo bar"; gsub(/o/, "[&]", s); print s; s = "foo"; gsub(/o/, "\\\\&", s); print s}'` },
    { name: 'awk/gsub-record', script: `echo 'a b a' | awk '{n = gsub(/a/, "x"); print n, $0, $1}'; echo 'a b' | awk '{sub(/b/, "c d", $2); print; print NF}'` },
    { name: 'awk/gsub-anchor', script: `awk 'BEGIN {s = "aaa"; gsub(/^a/, "X", s); print s; s = "abc"; gsub(/$/, "!", s); print s; s = "a.b.c"; gsub(/\\./, "", s); print s}'` },
    { name: 'awk/match', script: `awk 'BEGIN {print match("foobar", /o+/), RSTART, RLENGTH; print match("abc", /z/), RSTART, RLENGTH; print match("abc", /^/), RLENGTH}'` },
    { name: 'awk/case', script: `awk 'BEGIN {print toupper("abc1"), tolower("ABC-D")}'` },
    { name: 'awk/math', script: `awk 'BEGIN {printf "%.4f %.4f %.4f %.4f %.4f %.4f\\n", sin(1), cos(0), atan2(1, 1) * 4, exp(1), log(10), sqrt(2)}'` },
    { name: 'awk/rand', script: `awk 'BEGIN {srand(42); a = rand(); print (a >= 0 && a < 1); x = srand(7); print srand(9)}'` },
    { name: 'awk/printf-int', script: `awk 'BEGIN {printf "%d|%5d|%-5d|%05d|%+d|% d|%.3d|%i\\n", 42.9, 42, 42, 42, 42, 42, 7, -3.9}'` },
    { name: 'awk/printf-radix', script: `awk 'BEGIN {printf "%o|%x|%X|%#o|%#x|%u\\n", 8, 255, 255, 8, 255, 42}'` },
    { name: 'awk/printf-float', script: `awk 'BEGIN {printf "%f|%.2f|%8.3f|%-8.1f|%e|%.2E|%g|%G|%g|%g\\n", 3.14159, 2.5, 3.14159, 2.25, 12345.678, 0.000123, 0.0001, 1e-5, 123456789, 100}'` },
    { name: 'awk/printf-round', script: `awk 'BEGIN {printf "%.0f %.0f %.0f %.2f %.1f\\n", 0.5, 1.5, 2.5, 0.125, 0.25}'` },
    { name: 'awk/printf-str', script: `awk 'BEGIN {printf "%s|%10s|%-10s|%.2s|%c|%c|%%\\n", "abc", "abc", "abc", "abc", 65, "hello"}'` },
    { name: 'awk/printf-star', script: `awk 'BEGIN {printf "%*d|%-*d|%.*f\\n", 5, 42, 4, 7, 2, 3.14159}'` },
    { name: 'awk/sprintf', script: `awk 'BEGIN {s = sprintf("%03d-%s", 7, "x"); print s, length(s)}'` },
    { name: 'awk/printf-parens', script: `awk 'BEGIN {printf("%s %s\\n", "a", "b"); print("x", "y"); print ("p")("q")}'` },
    { name: 'awk/escapes', script: `awk 'BEGIN {print "a\\tb\\\\c\\"d\\101\\n"}' | od -c` },
    { name: 'awk/v-option', script: `awk -v x=5 -v 'y=a\\tb' 'BEGIN {print x + 1, y}'; awk -vn=3 'BEGIN {print n * 2}'` },
    { name: 'awk/v-strnum', script: `awk -v x=10 -v y=9 'BEGIN {print (x > y)}'` },
    { name: 'awk/operand-assign', script: `printf 'a\\n' > f1; printf 'b\\n' > f2; awk '{print v, $0}' v=1 f1 v=2 f2; echo x | awk '{print v}' v=hello` },
    { name: 'awk/operand-assign-end', script: `printf 'a\\n' > f1; awk 'END {print v}' f1 v=last` },
    { name: 'awk/argv', script: `printf 'a\\n' > f1; awk 'BEGIN {for (i = 0; i < ARGC; i++) print i, ARGV[i]}' f1 x=1 | sed 1d; awk 'BEGIN {ARGV[1] = ""} {print}' nonexistent f1` },
    { name: 'awk/filename-fnr', script: `printf 'a\\nb\\n' > f1; printf 'c\\n' > f2; awk '{print FILENAME, NR, FNR}' f1 f2; awk 'FNR == 1 {print FILENAME}' f1 f2` },
    { name: 'awk/stdin-dash', script: `printf 'f\\n' > f1; echo s | awk '{print}' f1 - f1` },
    { name: 'awk/environ', script: `FOO=bar awk 'BEGIN {print ENVIRON["FOO"]}'` },
    { name: 'awk/f-option', script: `printf 'BEGIN {x = 1}\\n' > p1; printf 'END {print x, NR}\\n' > p2; printf 'a\\nb\\n' | awk -f p1 -f p2` },
    { name: 'awk/getline-plain', script: `seq 1 6 | awk 'NR == 1 {getline; print "after", $0, NR} NR == 3 {getline x; print "var", x, $0, NR}'` },
    { name: 'awk/getline-file', script: `printf 'l1\\nl2\\n' > g; awk 'BEGIN {while ((getline line < "g") > 0) n++; print n, line; close("g"); getline < "g"; print $0, NR; print (getline z < "missing")}'` },
    { name: 'awk/getline-cmd', script: `awk 'BEGIN {"echo hi" | getline; print $0; while (("echo a; echo b" | getline v) > 0) print "v=" v; print close("echo hi")}'` },
    { name: 'awk/getline-end', script: `echo x | awk 'END {print getline, $0}'` },
    { name: 'awk/print-redirect', script: `awk 'BEGIN {print "one" > "o"; print "two" > "o"; print "three" >> "o2"; close("o"); print "four" >> "o"}'; cat o o2` },
    { name: 'awk/print-pipe', script: `awk 'BEGIN {print "b" | "sort"; print "a" | "sort"; close("sort"); print "after"}'` },
    { name: 'awk/print-pipe-exit', script: `awk 'BEGIN {print "z\\ny" | "sort"}'; echo done` },
    { name: 'awk/system', script: `awk 'BEGIN {print "before"; r = system("echo inside; exit 3"); print "after", r}'` },
    { name: 'awk/stderr', script: `awk 'BEGIN {print "err" > "/dev/stderr"; print "out"}' 2>/dev/null` },
    {
        name: 'awk/comments-newlines', script: `awk '
        # comment
        BEGIN {
            x = 1 + \\
                2   # trailing
            if (x == 3 &&
                1)
                print "ok"
            else
                print "no"
        }'`,
    },
    { name: 'awk/semicolons', script: `awk 'BEGIN { if (1) print "a"; else print "b"; ; print "c" }; END{print "d"}' < /dev/null` },
    { name: 'awk/syntax-error', script: `awk 'BEGIN { print ( }' 2>/dev/null; echo st=$?; awk '{print $1' 2>/dev/null; echo st=$?` },
    { name: 'awk/missing-file', script: `awk '{print}' nofile 2>/dev/null; echo st=$?` },
    { name: 'awk/regex-pattern-only', script: `printf 'apple\\nbanana\\ncherry\\n' | awk '/an/; /^c/ {print "C:" $0}'` },
    { name: 'awk/numeric-output', script: `echo '0.10 1e2 007' | awk '{print $1, $2, $3; print $1 + 0, $2 + 0, $3 + 0}'` },
    { name: 'awk/convfmt-key', script: `awk 'BEGIN {a[0.1 + 0.2] = 1; for (k in a) print k; b[01] = "x"; print b["1"]}'` },
    { name: 'awk/word-count', script: `printf 'the cat the dog\\nthe end\\n' | awk '{for (i = 1; i <= NF; i++) w[$i]++} END {for (k in w) print w[k], k}' | sort -k2` },
    { name: 'awk/columns-csv', script: `printf 'id,name,score\\n1,ann,90\\n2,bo,85\\n' | awk -F, 'NR > 1 {sum += $3; printf "%-4s %5.1f\\n", $2, $3} END {print "avg", sum / (NR - 1)}'` },
    { name: 'awk/uniq-lines', script: `printf 'a\\nb\\na\\nc\\nb\\n' | awk '!seen[$0]++'` },
    { name: 'awk/reverse-fields', script: `echo 'a b c d' | awk '{for (i = NF; i > 0; i--) printf "%s%s", $i, (i > 1 ? OFS : ORS)}'` },
    { name: 'awk/in-precedence', script: `awk 'BEGIN {a["x"]; print ("y" in a) + 1; if (!("y" in a)) print "no y"}'` },
    { name: 'awk/regex-as-value', script: `echo abc | awk '{x = /b/; y = /z/; print x, y}'` },
    { name: 'awk/dollar-expr', script: `echo 'a b c' | awk '{i = 1; print $i, $(i + 1), $NF, $(NF - 1); print $i++; print i}'` },
    { name: 'awk/nextfile', script: `printf 'a\\nb\\n' > f1; printf 'c\\nd\\n' > f2; awk 'FNR == 2 {nextfile} {print FILENAME, $0}' f1 f2` },
    { name: 'awk/delete-all', script: `awk 'BEGIN {a[1]; a[2]; delete a; print length(a); a[3] = 1; print length(a)}'` },
    { name: 'awk/getline-var-strnum', script: `printf '10\\n9\\n' | awk 'NR == 1 {getline x; print ($0 > x)}'` },
    { name: 'awk/split-dot', script: `awk 'BEGIN {n = split("a.b.c", p, "."); print n, p[2]}'` },
    { name: 'awk/length-noparen', script: `printf 'abc\\nde\\n' | awk 'length > 2'; echo abcd | awk '{n = length; print n * 2}'` },
    { name: 'awk/printf-c-strnum', script: `echo 65 | awk '{printf "%c|%c\\n", $1 + 0, "B"}'` },
    { name: 'awk/regex-dynamic-special', script: `awk 'BEGIN {s = "a+b"; gsub("\\\\+", "-", s); print s; t = "x.y"; sub(".", "_", t); print t}'` },
    { name: 'awk/assign-field-nf', script: `echo 'a b c' | awk '{$2 = ""; print; print NF}'` },
    { name: 'awk/while-getline-file-count', script: `seq 1 5 > n; awk 'BEGIN {while ((getline l < "n") > 0) s += l; print s}'` },
    { name: 'awk/pipe-to-cat-order', script: `awk 'BEGIN {print "1"; print "2" | "cat"; close("cat"); print "3"}'` },
    { name: 'awk/printf-g-big', script: `awk 'BEGIN {printf "%g %g %g %.3g %#g\\n", 1e100, 123456, 1234567, 0.0001234, 1}'` },
    { name: 'awk/exp-notation', script: `awk 'BEGIN {print 1e300 * 10, 1e-5, 123456789012, 0.000001}'` },
    { name: 'awk/string-to-num', script: `awk 'BEGIN {print "3.5abc" + 1, " 12 " + 0, ".5" + 0, "-1e2x" * 1, "abc" + 0, "+4" + 0}'` },
];

export const UTILITY_CASES: DifferentialCase[] = [
    // od
    ...['', '-c', '-b', '-x', '-d', '-s', '-o', '-t x1', '-t d1', '-t u4', '-t o4', '-t x8', '-t f4', '-t f8', '-a',
        '-An -tx1', '-Ad -tx2', '-Ax -c', '-c -tx1', '-j3 -N4 -c', '-tx1z', '-w4 -tx1', '-t d2 -t c', '-v -c', '-t u1 -t a']
        .map((opts, i) => ({ name: `od/${i}:${opts || 'default'}`, script: `${SAMPLE}${REPEAT}od ${opts} s; od ${opts} r` })),
    { name: 'od/stdin', script: `printf 'xyz' | od -c` },
    { name: 'od/empty', script: `: > e; od e; od -c < e` },
    { name: 'od/missing', script: `od nofile; echo st=$?` },
    { name: 'od/two-files', script: `printf ab > 1; printf cd > 2; od -c 1 2` },
    // cmp
    { name: 'cmp/same', script: `printf 'abc\\n' > a; printf 'abc\\n' > b; cmp a b; echo st=$?` },
    { name: 'cmp/differ', script: `printf 'line1\\nabc\\n' > a; printf 'line1\\nabd\\n' > b; cmp a b; echo st=$?` },
    { name: 'cmp/silent', script: `printf 'x' > a; printf 'y' > b; cmp -s a b; echo st=$?` },
    { name: 'cmp/list', script: `printf 'abcd' > a; printf 'abXY' > b; cmp -l a b; echo st=$?` },
    { name: 'cmp/eof', script: `printf 'ab' > a; printf 'abc' > b; cmp a b 2>&1; echo st=$?; : > e; cmp e b 2>&1; echo st=$?` },
    { name: 'cmp/skip', script: `printf 'xa' > a; printf 'ya' > b; cmp a b 1 1; echo st=$?; cmp -i 1 a b; echo st=$?` },
    { name: 'cmp/limit', script: `printf 'ab' > a; printf 'ac' > b; cmp -n 1 a b; echo st=$?` },
    { name: 'cmp/stdin', script: `printf 'q' > b; printf 'q' | cmp - b; echo st=$?` },
    { name: 'cmp/missing', script: `cmp nope b 2>/dev/null; echo st=$?` },
    // wc
    { name: 'wc/default', script: `printf 'one two\\nthree\\n' > f; wc f; wc < f; wc -l f; wc -w < f; wc -c f` },
    { name: 'wc/multi', script: `printf 'a\\n' > x; printf 'b c\\nd\\n' > y; wc x y; wc -l x y` },
    { name: 'wc/chars', script: `printf 'h\\303\\251llo\\n' > u; wc -c u; wc -m u` },
    { name: 'wc/stdin-pipe', script: `printf 'a b c' | wc; printf '' | wc -l` },
    // cksum
    { name: 'cksum/basic', script: `printf 'hello\\n' > h; cksum h; printf '' | cksum; printf 'x' | cksum; seq 1 1000 > s 2>/dev/null || printf '1\\n2\\n' > s; cksum s` },
    // nl
    { name: 'nl/default', script: `printf 'a\\n\\nb\\n' | nl` },
    { name: 'nl/all', script: `printf 'a\\n\\nb\\n' | nl -ba` },
    { name: 'nl/opts', script: `printf 'a\\nb\\nc\\n' | nl -i 2 -v 10 -w 3 -s ': ' -n rz` },
    { name: 'nl/ln', script: `printf 'a\\nb\\n' | nl -n ln` },
    { name: 'nl/pattern', script: `printf 'apple\\nbanana\\ncherry\\n' | nl -b pa` },
    { name: 'nl/pages', script: `printf '\\\\:\\\\:\\\\:\\nhead\\n\\\\:\\\\:\\nbody1\\nbody2\\n\\\\:\\nfoot\\n' | nl -ha -fa` },
    { name: 'nl/join', script: `printf 'a\\n\\n\\n\\n\\nb\\n' | nl -ba -l 2` },
    // strings
    { name: 'strings/basic', script: `printf 'abc\\000hello\\001\\002world!\\377xy\\ttabbed\\n' > b; strings b; strings -n 2 b; strings -t x b; strings -t d -n 6 b` },
    { name: 'strings/stdin', script: `printf 'zz\\000longer\\000' | strings` },
    // expand / unexpand
    { name: 'expand/default', script: `printf 'a\\tb\\t\\tc\\n\\tx\\n' | expand | od -c` },
    { name: 'expand/t4', script: `printf 'a\\tb\\n12345\\tc\\n' | expand -t 4` },
    { name: 'expand/list', script: `printf 'a\\tb\\tc\\td\\n' | expand -t 3,7,12` },
    { name: 'unexpand/leading', script: `printf '        a       b\\n    c\\n' | unexpand | od -c` },
    { name: 'unexpand/all', script: `printf '        a       b\\n' | unexpand -a | od -c` },
    { name: 'unexpand/t4', script: `printf '    x   y\\n' | unexpand -t 4 | od -c` },
    // fold
    { name: 'fold/width', script: `printf 'abcdefghij\\nshort\\n' | fold -w 4` },
    { name: 'fold/spaces', script: `echo "a b c d" | fold -w 3 -s; echo "the quick brown fox jumps" | fold -s -w 10` },
    { name: 'fold/tabs', script: `printf 'a\\tbcdefghijk\\n' | fold -w 10 | od -c` },
    { name: 'fold/bytes', script: `printf 'abcdef\\n' | fold -b -w 2` },
    { name: 'fold/zero', script: `echo x | fold -w 0; echo st=$?` },
    // tsort
    { name: 'tsort/basic', script: `printf 'a b\\nb c\\na d\\nd c\\ne e\\n' | tsort` },
    { name: 'tsort/chain', script: `echo 'shirt tie tie jacket belt jacket pants shoes pants belt socks shoes' | tsort` },
    { name: 'tsort/cycle', script: `printf 'a b\\nb a\\n' | tsort 2>/dev/null; echo st=$?` },
    { name: 'tsort/odd', script: `echo 'a b c' | tsort 2>/dev/null; echo st=$?` },
    // ln / link / unlink / readlink / realpath / mkfifo
    { name: 'ln/hard', script: `echo x > f; ln f h; ls -i f h | awk '{print $1}' | uniq | wc -l; cat h` },
    { name: 'ln/symlink', script: `echo x > f; ln -s f s; readlink s; cat s; ln -s nowhere dangling; readlink dangling; cat dangling 2>/dev/null; echo st=$?` },
    { name: 'ln/exists', script: `touch a b; ln a b 2>&1; echo st=$?; ln -f a b; echo st=$?` },
    { name: 'ln/into-dir', script: `touch f1 f2; mkdir d; ln f1 f2 d; ls d; ln -s ../f1 d/sl; cat d/sl; echo ok` },
    { name: 'ln/dir-hard', script: `mkdir d; ln d d2 2>&1; echo st=$?` },
    { name: 'ln/multi-not-dir', script: `touch a b c; ln a b c 2>&1; echo st=$?` },
    { name: 'link/basic', script: `echo y > f; link f g; cat g; link f g 2>/dev/null; echo st=$?; link f 2>/dev/null; echo st=$?` },
    { name: 'unlink/basic', script: `touch f; unlink f; [ -e f ] || echo gone; unlink f 2>/dev/null; echo st=$?; mkdir d; unlink d 2>/dev/null; echo st=$?; touch a b; unlink a b 2>/dev/null; echo st=$?` },
    { name: 'readlink/canon', script: `mkdir -p a/b; touch a/b/f; ln -s a/b lb; ln -s lb/f lf; readlink lf; readlink -f lf | sed "s|$PWD|PWD|"; readlink -e nope; echo st=$?; readlink -m nope/x | sed "s|$PWD|PWD|"; readlink -f nope | sed "s|$PWD|PWD|"; readlink -f nope/x; echo st=$?` },
    { name: 'readlink/plain', script: `touch f; readlink f; echo st=$?; ln -s f l; readlink -n l; echo; readlink l l` },
    { name: 'realpath/basic', script: `mkdir -p x/y; touch x/y/f; ln -s x/y ly; realpath ly/f | sed "s|$PWD|PWD|"; realpath -s ly/f | sed "s|$PWD|PWD|"; realpath . | sed "s|$PWD|PWD|"; realpath missing | sed "s|$PWD|PWD|"; realpath -e missing 2>/dev/null; echo st=$?; realpath -m a/../b/c | sed "s|$PWD|PWD|"` },
    { name: 'mkfifo/basic', script: `mkfifo p; ls -l p | cut -c1; mkfifo p 2>/dev/null; echo st=$?; mkfifo -m 600 q; ls -l q | cut -c1-10; [ -p q ] && echo fifo` },
    // sed
    { name: 'sed/subst', script: `printf 'hello world\\nfoo bar\\n' > f; sed 's/o/0/' f; sed 's/o/0/g' f; sed 's/o/0/2' f; sed -n 's/foo/X/p' f` },
    { name: 'sed/multi-e', script: `echo a | sed -e 's/a/b/' -e 's/b/c/'; echo a | sed 's/a/b/;s/b/d/'` },
    { name: 'sed/addresses', script: `printf '1\\n2\\n3\\n4\\n5\\n' > n; sed -n '2,4p' n; sed '3d' n; sed -n '/3/,$p' n; sed '$d' n; sed -n '1~2p' n 2>/dev/null; sed '2!d' n` },
    { name: 'sed/regex', script: `echo 'abc123def' | sed 's/[0-9]\\{2\\}/X/'; echo 'aaa' | sed 's/a*/X/'; echo 'hello' | sed 's/\\(h\\)\\(e\\)/\\2\\1/'; echo 'path/to/x' | sed 's|/|:|g'; echo 'one two' | sed -E 's/(\\w+) (\\w+)/\\2 \\1/'` },
    { name: 'sed/amp-case', script: `echo hello | sed 's/l*/[&]/g'; echo Hello | sed 's/hello/X/I'` },
    { name: 'sed/commands', script: `printf 'a\\nb\\nc\\n' > f; sed '2i\\
inserted' f; sed '2a\\
appended' f; sed '2c\\
changed' f; sed -n '$=' f; sed 'y/abc/xyz/' f` },
    { name: 'sed/hold', script: `printf '1\\n2\\n3\\n' | sed -n '1!G;h;$p'; printf 'a\\nb\\n' | sed 'N;s/\\n/,/'` },
    { name: 'sed/inplace', script: `printf 'x\\n' > f; sed -i 's/x/y/' f; cat f` },
    { name: 'sed/quit', script: `printf '1\\n2\\n3\\n' | sed 2q; printf '1\\n2\\n' | sed -n '/2/{p;q;}'` },
    { name: 'sed/script-file', script: `printf 's/a/b/\\ns/b/c/\\n' > s.sed; echo a | sed -f s.sed` },
    // tr
    { name: 'tr/basic', script: `echo hello | tr a-z A-Z; echo hello | tr -d l; echo 'aabbcc' | tr -s abc; echo hello | tr -c le x; echo hello | tr -cd l; echo 'a b' | tr ' ' '\\n'` },
    { name: 'tr/classes', script: `echo 'Hello World 123' | tr '[:lower:]' '[:upper:]'; echo 'Hello 123' | tr -d '[:digit:]'; echo 'a  b   c' | tr -s '[:space:]'; echo abc | tr 'abc' 'x'; echo abcd | tr 'a-d' '[x*]'` },
    { name: 'tr/escapes', script: `printf 'a\\tb\\n' | tr '\\t' ' '; echo abc | tr '\\141' 'z'` },
    // split / csplit
    { name: 'split/lines', script: `seq 1 25 > f; split -l 10 f; ls x*; cat xab; split -l 10 -a 3 f p.; ls p.*` },
    { name: 'split/bytes', script: `printf '1234567' > f; split -b 3 f; for x in xa*; do printf '%s:' $x; cat $x; echo; done` },
    { name: 'split/default', script: `seq 1 2500 > f; split f; wc -l xa*` },
    { name: 'split/stdin-prefix', script: `seq 1 4 | split -l 2 - part; cat partaa; ls part*` },
    { name: 'split/numeric', script: `seq 1 4 > f; split -d -l 1 f; ls x*` },
    { name: 'csplit/line', script: `printf 'a\\nb\\nc\\n' > f; csplit f 2; cat xx00; echo --; cat xx01` },
    { name: 'csplit/regex', script: `printf 'h1\\nx\\nh2\\ny\\nh3\\n' > f; csplit -s f '/^h/' '{*}'; ls xx*; cat xx02` },
    { name: 'csplit/opts', script: `seq 1 6 > f; csplit -f part -n 3 f 3 5; ls part*; csplit -k f 99 2>/dev/null; echo st=$?; ls xx* 2>/dev/null | wc -l` },
    { name: 'csplit/offset', script: `seq 1 8 > f; csplit -s f '/4/+1' '%7%'; cat xx00; echo --; cat xx01` },
    { name: 'csplit/missing', script: `csplit nofile 1 2>/dev/null; echo st=$?` },
    // paste / join / comm
    { name: 'paste/basic', script: `printf '1\\n2\\n3\\n' > a; printf 'x\\ny\\n' > b; paste a b; paste -d, a b; paste -s a b; paste -s -d ':;' a; paste -d ':;' a b a` },
    { name: 'paste/stdin', script: `printf '1\\n2\\n3\\n4\\n' | paste - -; printf 'a\\nb\\n' | paste -s -` },
    { name: 'join/basic', script: `printf '1 a\\n2 b\\n3 c\\n' > f1; printf '1 x\\n3 z\\n4 w\\n' > f2; join f1 f2; join -a 1 f1 f2; join -v 2 f1 f2; join -o 1.2,2.2 f1 f2; join -o 0,2.2 -a1 -e NONE f1 f2` },
    { name: 'join/fields', script: `printf 'a:1\\nb:2\\n' > f1; printf '1:x\\n2:y\\n' > f2; join -t: -1 2 -2 1 f1 f2` },
    { name: 'comm/basic', script: `printf 'a\\nb\\nd\\n' > x; printf 'b\\nc\\nd\\n' > y; comm x y; comm -12 x y; comm -3 x y; echo b | comm - y` },
    // uname / sleep / pathchk / dirname
    { name: 'uname/errors', script: `uname -z 2>/dev/null; echo st=$?; uname extra 2>/dev/null; echo st=$?; uname -s | wc -l` },
    { name: 'sleep/errors', script: `sleep -1 2>/dev/null; echo st=$?; sleep x 2>/dev/null; echo st=$?; sleep 0 0; echo st=$?; sleep; echo st=$?` },
    { name: 'pathchk/basic', script: `pathchk a/b; echo st=$?; pathchk ''; echo st=$?; pathchk -p 'a b'; echo st=$?; pathchk -p 'ok_name'; echo st=$?; pathchk $(printf '%0300d' 0); echo st=$?` },
    { name: 'dirname/multi', script: `dirname a/b c/d /x` },
    // iconv
    { name: 'iconv/basic', script: `printf 'caf\\303\\251\\n' | iconv -f UTF-8 -t ISO-8859-1 | od -An -tx1; printf 'caf\\351\\n' | iconv -f ISO-8859-1 -t UTF-8; iconv -f JUNK -t ASCII /dev/null 2>/dev/null; echo st=$?; printf 'x\\n' | iconv -f ascii -t utf-8` },
    ...AWK_CASES,
];
