/**
 * printf - write formatted output (POSIX XCU printf).
 *
 * Format escapes (\n, \t, \ddd...), conversions %d %i %o %u %x %X %f %F
 * %e %E %g %G %c %s %b %% with flags (-+ #0), width and precision
 * (including `*`). The format is reused while arguments remain.
 * Numeric arguments may be C constants (0x1f, 017) or 'c / "c (char code).
 */
import { ICommand, CommandResponse } from '../ICommand';
import { ProcessContext } from '../../entities/ProcessContext';
import { TerminalState } from '../../entities/TerminalState';
import { FileSystemService } from '../../services/FileSystemService';

/**
 * Text produced by printf: characters from arguments/format are UTF-8
 * encoded, while escape-generated bytes are marked with BYTE_MARK so they
 * are emitted raw.
 */
const BYTE_MARK = 0xf700; // private-use area: U+F700 + byte

export function markByte(byte: number): string {
    return byte < 0x80 ? String.fromCharCode(byte) : String.fromCharCode(BYTE_MARK + byte);
}

export function toByteString(s: string): string {
    const bytes: number[] = [];
    const enc = new TextEncoder();
    for (const ch of s) {
        const cp = ch.codePointAt(0)!;
        if (cp >= BYTE_MARK && cp <= BYTE_MARK + 0xff) bytes.push(cp - BYTE_MARK);
        else bytes.push(...enc.encode(ch));
    }
    let out = '';
    for (const b of bytes) out += String.fromCharCode(b);
    return out;
}

const ESCAPES: Record<string, string> = {
    '\\': '\\', a: '\x07', b: '\b', f: '\f', n: '\n', r: '\r', t: '\t', v: '\v', '"': '"', "'": "'",
};

/** Expands backslash escapes. `bMode` is %b semantics (\0ddd octal, \c stops). */
export function expandEscapes(s: string, bMode = false): { text: string; stop: boolean } {
    let out = '';
    for (let i = 0; i < s.length; i++) {
        const c = s[i];
        if (c !== '\\' || i + 1 >= s.length) { out += c; continue; }
        const n = s[i + 1];
        if (bMode && n === 'c') return { text: out, stop: true };
        if (/[0-7]/.test(n)) {
            const max = bMode && n === '0' ? 4 : 3;
            let j = i + 1;
            let digits = '';
            while (j < s.length && digits.length < max && /[0-7]/.test(s[j])) digits += s[j++];
            out += markByte(parseInt(digits, 8) & 0xff);
            i = j - 1;
            continue;
        }
        if (ESCAPES[n] !== undefined) { out += ESCAPES[n]; i++; continue; }
        const hex = n === 'x' ? /^[0-9a-fA-F]{1,2}/.exec(s.substring(i + 2)) : null;
        if (hex) { out += markByte(parseInt(hex[0], 16)); i += 1 + hex[0].length; continue; }
        out += c;
    }
    return { text: out, stop: false };
}

interface Spec {
    flags: string;
    width?: number;
    precision?: number;
    conv: string;
}

export class PrintfCommand implements ICommand {
    constructor(private fs?: FileSystemService) { }

    execute(args: string[], _context: ProcessContext, state: TerminalState): CommandResponse {
        if (args.length === 0) {
            return { output: '', stderr: 'printf: usage: printf format [argument...]\n', exitCode: 2, newState: state };
        }
        const format = args[0];
        const params = args.slice(1);
        const errors: string[] = [];
        let index = 0;
        let output = '';

        const next = (): string | undefined => (index < params.length ? params[index++] : undefined);
        const num = (raw: string | undefined, integer: boolean): number => {
            if (raw === undefined || raw === '') return 0;
            if (/^['"]/.test(raw)) return raw.length > 1 ? raw.codePointAt(1)! : 0;
            const t = raw.trim();
            let v: number;
            if (integer) {
                const m = /^([-+]?)(0[xX][0-9a-fA-F]+|0[0-7]*|[1-9][0-9]*)/.exec(t);
                if (!m) { errors.push(`printf: '${raw}': expected numeric value`); return 0; }
                const body = m[2];
                v = /^0[xX]/.test(body) ? parseInt(body, 16) : body.length > 1 && body[0] === '0' ? parseInt(body, 8) : parseInt(body, 10);
                if (m[1] === '-') v = -v;
                if (m[0].length !== t.length) errors.push(`printf: '${raw}': value not completely converted`);
            } else {
                v = parseFloat(t);
                if (isNaN(v)) { errors.push(`printf: '${raw}': expected numeric value`); return 0; }
            }
            return v;
        };

        do {
            const start = index;
            const { text, stop } = this.render(format, next, num);
            output += text;
            if (stop) break;
            if (index === start) break; // format consumes no arguments
        } while (index < params.length);

        return {
            // Escapes yield raw bytes (\377), arguments are text: emit UTF-8 bytes.
            output: toByteString(output),
            binary: true,
            stderr: errors.length ? errors.join('\n') + '\n' : undefined,
            exitCode: errors.length ? 1 : 0,
            newState: state,
        };
    }

    private render(
        format: string,
        next: () => string | undefined,
        num: (raw: string | undefined, integer: boolean) => number
    ): { text: string; stop: boolean } {
        let out = '';
        for (let i = 0; i < format.length; i++) {
            const c = format[i];
            if (c === '\\' && format[i + 1] === 'c') return { text: out, stop: true }; // \c: no further output
            if (c === '\\') {
                // One escape at a time so that \c etc. are handled in place.
                let j = i + 1;
                if (/[0-7]/.test(format[j] ?? '')) { while (j < format.length && j < i + 4 && /[0-7]/.test(format[j])) j++; }
                else if (format[j] === 'x' && /[0-9a-fA-F]/.test(format[j + 1] ?? '')) { j += 2; if (/[0-9a-fA-F]/.test(format[j] ?? '')) j++; }
                else j++;
                out += expandEscapes(format.substring(i, j)).text;
                i = j - 1;
                continue;
            }
            if (c !== '%') { out += c; continue; }
            if (format[i + 1] === '%') { out += '%'; i++; continue; }

            const m = /^%([-+ #0]*)(\*|[0-9]+)?(?:\.(\*|[0-9]*))?([diouxXfFeEgGcsb])/.exec(format.substring(i));
            if (!m) { out += c; continue; }
            i += m[0].length - 1;

            const spec: Spec = { flags: m[1], conv: m[4] };
            if (m[2] === '*') spec.width = num(next(), true);
            else if (m[2] !== undefined) spec.width = parseInt(m[2], 10);
            if (m[3] === '*') spec.precision = num(next(), true);
            else if (m[3] !== undefined) spec.precision = m[3] === '' ? 0 : parseInt(m[3], 10);
            if (spec.width !== undefined && spec.width < 0) { spec.flags += '-'; spec.width = -spec.width; }

            if (spec.conv === 'b') {
                const r = expandEscapes(next() ?? '', true);
                out += this.pad(this.truncate(r.text, spec), spec, false);
                if (r.stop) return { text: out, stop: true };
                continue;
            }
            out += this.convert(spec, next, num);
        }
        return { text: out, stop: false };
    }

    private truncate(s: string, spec: Spec): string {
        return spec.precision !== undefined ? s.substring(0, spec.precision) : s;
    }

    private pad(body: string, spec: Spec, numeric: boolean, sign = ''): string {
        const width = spec.width ?? 0;
        const len = sign.length + body.length;
        if (len >= width) return sign + body;
        if (spec.flags.includes('-')) return sign + body + ' '.repeat(width - len);
        if (numeric && spec.flags.includes('0') && !(spec.precision !== undefined && /[diouxX]/.test(spec.conv))) {
            return sign + '0'.repeat(width - len) + body;
        }
        return ' '.repeat(width - len) + sign + body;
    }

    private convert(spec: Spec, next: () => string | undefined, num: (raw: string | undefined, integer: boolean) => number): string {
        const { conv, flags } = spec;
        if (conv === 's') return this.pad(this.truncate(next() ?? '', spec), spec, false);
        if (conv === 'c') return this.pad((next() ?? '').charAt(0), spec, false);

        if (/[diouxX]/.test(conv)) {
            let v = Math.trunc(num(next(), true));
            let sign = '';
            let digits: string;
            if (conv === 'd' || conv === 'i') {
                if (v < 0) { sign = '-'; v = -v; }
                else if (flags.includes('+')) sign = '+';
                else if (flags.includes(' ')) sign = ' ';
                digits = String(v);
            } else {
                const u = v < 0 ? BigInt.asUintN(64, BigInt(v)) : BigInt(v);
                digits = conv === 'o' ? u.toString(8) : conv === 'u' ? u.toString(10) : u.toString(16);
                if (conv === 'X') digits = digits.toUpperCase();
                if (flags.includes('#') && u !== 0n) {
                    if (conv === 'o' && !digits.startsWith('0')) digits = '0' + digits;
                    if (conv === 'x') sign = '0x';
                    if (conv === 'X') sign = '0X';
                }
            }
            if (spec.precision !== undefined) {
                digits = spec.precision === 0 && digits === '0' ? '' : digits.padStart(spec.precision, '0');
            }
            return this.pad(digits, spec, true, sign);
        }

        // Floating point
        let v = num(next(), false);
        let sign = '';
        if (v < 0 || Object.is(v, -0)) { sign = '-'; v = -v; }
        else if (flags.includes('+')) sign = '+';
        else if (flags.includes(' ')) sign = ' ';
        const p = spec.precision ?? 6;
        let body: string;
        if (!isFinite(v)) body = isNaN(v) ? 'nan' : 'inf';
        else if (conv === 'f' || conv === 'F') body = v.toFixed(p);
        else if (conv === 'e' || conv === 'E') body = this.exp(v, p);
        else body = this.general(v, p === 0 ? 1 : p, flags.includes('#'));
        if (conv === 'F' || conv === 'E' || conv === 'G') body = body.toUpperCase();
        return this.pad(body, spec, true, sign);
    }

    /** C-style %e: mantissa with p decimals and an at-least-two-digit exponent. */
    private exp(v: number, p: number): string {
        const [m, e] = v.toExponential(p).split('e');
        const n = parseInt(e, 10);
        return `${m}e${n < 0 ? '-' : '+'}${String(Math.abs(n)).padStart(2, '0')}`;
    }

    private general(v: number, p: number, alt: boolean): string {
        if (v === 0) return alt ? (0).toFixed(p - 1) : '0';
        const x = Math.floor(Math.log10(Math.abs(Number(v.toExponential(p - 1)))));
        let s = x < -4 || x >= p ? this.exp(v, p - 1) : v.toFixed(Math.max(0, p - 1 - x));
        if (!alt) {
            s = s.replace(/(\.[0-9]*?)0+(e|$)/, '$1$2').replace(/\.(e|$)/, '$1');
        }
        return s;
    }
}
