/**
 * CoreUtilsModule - Domain Layer
 *
 * Registers the standard POSIX core utilities.
 *
 * Pillar: The Master’s Tool (Module Pattern)
 */

import { CommandModule } from './CommandModule';
import { CommandRegistry } from '../commands/CommandRegistry';
import { FileSystem } from '../entities/FileSystem';
import { FileSystemService } from '../services/FileSystemService';
import { IdentityService } from '../services/IdentityService';

import { LsCommand } from '../commands/core/LsCommand';
import { CdCommand } from '../commands/core/CdCommand';
import { PwdCommand } from '../commands/core/PwdCommand';
import { CatCommand } from '../commands/core/CatCommand';
import { GrepCommand } from '../commands/core/GrepCommand';
import { MkdirCommand } from '../commands/core/MkdirCommand';
import { TouchCommand } from '../commands/core/TouchCommand';
import { RmCommand } from '../commands/core/RmCommand';
import { CpCommand } from '../commands/core/CpCommand';
import { MvCommand } from '../commands/core/MvCommand';
import { EchoCommand } from '../commands/core/EchoCommand';
import { HeadCommand } from '../commands/core/HeadCommand';
import { TailCommand } from '../commands/core/TailCommand';
import { WcCommand } from '../commands/core/WcCommand';
import { ChmodCommand } from '../commands/core/ChmodCommand';
import { ChownCommand } from '../commands/core/ChownCommand';
import { DuCommand } from '../commands/core/DuCommand';
import { LnCommand } from '../commands/core/LnCommand';
import { DfCommand } from '../commands/core/DfCommand';
import { FindCommand } from '../commands/core/FindCommand';
import { SedCommand } from '../commands/core/SedCommand';
import { AwkCommand } from '../commands/core/AwkCommand';
import { XargsCommand } from '../commands/core/XargsCommand';
import { CutCommand } from '../commands/core/CutCommand';
import { TrCommand } from '../commands/core/TrCommand';
import { UniqCommand } from '../commands/core/UniqCommand';
import { SortCommand } from '../commands/core/SortCommand';
import { EdCommand } from '../commands/core/EdCommand';
import { CmpCommand } from '../commands/core/CmpCommand';
import { CommCommand } from '../commands/core/CommCommand';
import { DiffCommand } from '../commands/core/DiffCommand';
import { PasteCommand } from '../commands/core/PasteCommand';
import { TeeCommand } from '../commands/core/TeeCommand';
import { CksumCommand } from '../commands/core/CksumCommand';
import { FoldCommand } from '../commands/core/FoldCommand';
import { JoinCommand } from '../commands/core/JoinCommand';
import { NlCommand } from '../commands/core/NlCommand';
import { PrintfCommand } from '../commands/core/PrintfCommand';
import { SplitCommand } from '../commands/core/SplitCommand';
import { StringsCommand } from '../commands/core/StringsCommand';
import { ExpandCommand } from '../commands/core/ExpandCommand';
import { UnexpandCommand } from '../commands/core/UnexpandCommand';
import { TsortCommand } from '../commands/core/TsortCommand';
import { RmdirCommand } from '../commands/core/RmdirCommand';
import { LinkCommand } from '../commands/core/LinkCommand';
import { UnlinkCommand } from '../commands/core/UnlinkCommand';
import { ReadlinkCommand } from '../commands/core/ReadlinkCommand';
import { RealpathCommand } from '../commands/core/RealpathCommand';
import { SleepCommand } from '../commands/core/SleepCommand';
import { UnameCommand } from '../commands/core/UnameCommand';
import { LognameCommand } from '../commands/core/LognameCommand';
import { EnvCommand } from '../commands/core/EnvCommand';
import { CalCommand } from '../commands/core/CalCommand';
import { ExprCommand } from '../commands/core/ExprCommand';
import { TestCommand } from '../commands/core/TestCommand';
import { OdCommand } from '../commands/core/OdCommand';
import { UuencodeCommand } from '../commands/core/UuencodeCommand';
import { UudecodeCommand } from '../commands/core/UudecodeCommand';
import { WhoCommand } from '../commands/core/WhoCommand';
import { TtyCommand } from '../commands/core/TtyCommand';
import { IdCommand } from '../commands/core/IdCommand';
import { BasenameCommand } from '../commands/core/BasenameCommand';
import { DirnameCommand } from '../commands/core/DirnameCommand';
import { PathchkCommand } from '../commands/core/PathchkCommand';
import { TrueCommand } from '../commands/core/TrueCommand';
import { FalseCommand } from '../commands/core/FalseCommand';
import { TimeCommand } from '../commands/core/TimeCommand';
import { NohupCommand } from '../commands/core/NohupCommand';
import { NiceCommand } from '../commands/core/NiceCommand';
import { ChgrpCommand } from '../commands/core/ChgrpCommand';
import { AliasCommand } from '../commands/core/AliasCommand';
import { UnaliasCommand } from '../commands/core/UnaliasCommand';
import { TypeCommand } from '../commands/core/TypeCommand';
import { PrCommand } from '../commands/core/PrCommand';
import { CompressCommand } from '../commands/core/CompressCommand';
import { UncompressCommand } from '../commands/core/UncompressCommand';
import { ZcatCommand } from '../commands/core/ZcatCommand';
import { AsaCommand } from '../commands/core/AsaCommand';
import { DdCommand } from '../commands/core/DdCommand';
import { IconvCommand } from '../commands/core/IconvCommand';
import { JobsCommand } from '../commands/core/JobsCommand';
import { KillCommand } from '../commands/core/KillCommand';
import { PsCommand } from '../commands/core/PsCommand';
import { WaitCommand } from '../commands/core/WaitCommand';
import { AtCommand } from '../commands/core/AtCommand';
import { BatchCommand } from '../commands/core/BatchCommand';
import { CrontabCommand } from '../commands/core/CrontabCommand';
import { MailxCommand } from '../commands/core/MailxCommand';
import { MesgCommand } from '../commands/core/MesgCommand';
import { TalkCommand } from '../commands/core/TalkCommand';
import { WriteCommand } from '../commands/core/WriteCommand';
import { BcCommand } from '../commands/core/BcCommand';
import { GetconfCommand } from '../commands/core/GetconfCommand';
import { LoggerCommand } from '../commands/core/LoggerCommand';
import { ManCommand } from '../commands/core/ManCommand';
import { TabsCommand } from '../commands/core/TabsCommand';
import { TputCommand } from '../commands/core/TputCommand';
import { MkfifoCommand } from '../commands/core/MkfifoCommand';
import { FileCommand } from '../commands/core/FileCommand';
import { TimeoutCommand } from '../commands/core/TimeoutCommand';
import { NullCommand } from '../commands/core/NullCommand';
import { ExitCommand } from '../commands/core/ExitCommand';
import { ShCommand } from '../commands/core/ShCommand';
import { UmaskCommand } from '../commands/core/UmaskCommand';
import { TimesCommand } from '../commands/core/TimesCommand';
import { MoreCommand } from '../commands/core/MoreCommand';
import { StripCommand } from '../commands/core/StripCommand';
import { UnsetCommand } from '../commands/core/UnsetCommand';
import { ExportCommand } from '../commands/core/ExportCommand';
import { ReadonlyCommand } from '../commands/core/ReadonlyCommand';
import { ExecCommand } from '../commands/core/ExecCommand';
import { EvalCommand } from '../commands/core/EvalCommand';
import { BreakCommand } from '../commands/core/BreakCommand';
import { ContinueCommand } from '../commands/core/ContinueCommand';
import { HashCommand } from '../commands/core/HashCommand';
import { TrapCommand } from '../commands/core/TrapCommand';
import { GetoptsCommand } from '../commands/core/GetoptsCommand';
import { SttyCommand } from '../commands/core/SttyCommand';
import { UlimitCommand } from '../commands/core/UlimitCommand';
import { FcCommand } from '../commands/core/FcCommand';
import { FgCommand } from '../commands/core/FgCommand';
import { BgCommand } from '../commands/core/BgCommand';
import { ShiftCommand } from '../commands/core/ShiftCommand';
import { ReadCommand } from '../commands/core/ReadCommand';
import { ReturnCommand } from '../commands/core/ReturnCommand';
import { CommandCommand } from '../commands/core/CommandCommand';
import { DotCommand } from '../commands/core/DotCommand';
import { SetCommand } from '../commands/core/SetCommand';
import { ViCommand } from '../commands/core/ViCommand';
import { ExCommand } from '../commands/core/ExCommand';
import { MakeCommand } from '../commands/core/MakeCommand';
import { ArCommand } from '../commands/core/ArCommand';
import { LexCommand } from '../commands/core/LexCommand';
import { YaccCommand } from '../commands/core/YaccCommand';
import { M4Command } from '../commands/core/M4Command';
import { NmCommand } from '../commands/core/NmCommand';
import { PatchCommand } from '../commands/core/PatchCommand';
import { PaxCommand } from '../commands/core/PaxCommand';
import { LpCommand } from '../commands/core/LpCommand';
import { ReniceCommand } from '../commands/core/ReniceCommand';
import { AdminCommand } from '../commands/core/AdminCommand';
import { C17Command } from '../commands/core/C17Command';
import { CflowCommand } from '../commands/core/CflowCommand';
import { CsplitCommand } from '../commands/core/CsplitCommand';
import { CtagsCommand } from '../commands/core/CtagsCommand';
import { CxrefCommand } from '../commands/core/CxrefCommand';
import { DeltaCommand } from '../commands/core/DeltaCommand';
import { FuserCommand } from '../commands/core/FuserCommand';
import { GencatCommand } from '../commands/core/GencatCommand';
import { GetCommand } from '../commands/core/GetCommand';
import { GettextCommand } from '../commands/core/GettextCommand';
import { IpcrmCommand } from '../commands/core/IpcrmCommand';
import { IpcsCommand } from '../commands/core/IpcsCommand';
import { LocaleCommand } from '../commands/core/LocaleCommand';
import { LocaledefCommand } from '../commands/core/LocaledefCommand';
import { MsgfmtCommand } from '../commands/core/MsgfmtCommand';
import { NewgrpCommand } from '../commands/core/NewgrpCommand';
import { NgettextCommand } from '../commands/core/NgettextCommand';
import { PrsCommand } from '../commands/core/PrsCommand';
import { RmdelCommand } from '../commands/core/RmdelCommand';
import { SactCommand } from '../commands/core/SactCommand';
import { SccsCommand } from '../commands/core/SccsCommand';
import { UngetCommand } from '../commands/core/UngetCommand';
import { UucpCommand } from '../commands/core/UucpCommand';
import { UustatCommand } from '../commands/core/UustatCommand';
import { UuxCommand } from '../commands/core/UuxCommand';
import { ValCommand } from '../commands/core/ValCommand';
import { WhatCommand } from '../commands/core/WhatCommand';
import { XgettextCommand } from '../commands/core/XgettextCommand';
import { GzipCommand } from '../commands/core/GzipCommand';
import { GunzipCommand } from '../commands/core/GunzipCommand';
import { TarCommand } from '../commands/core/TarCommand';
import { CpioCommand } from '../commands/core/CpioCommand';
import { WasmCompilerService } from '../../infrastructure/services/WasmCompilerService';
import { GccCommand } from '../commands/core/GccCommand';
import { WhoamiCommand } from '../commands/core/WhoamiCommand';
import { DateCommand } from '../commands/core/DateCommand';
import { GuiCommand } from '../commands/special/GuiCommand';
import { DispatchCommand } from '../commands/special/DispatchCommand';
import { ScpCommand } from '../commands/core/ScpCommand';

export class CoreUtilsModule implements CommandModule {
    private fsService: FileSystemService;

    constructor(private fs: FileSystem, private identityService: IdentityService) {
        this.fsService = new FileSystemService(fs);
    }

    register(registry: CommandRegistry): void {
        const fsService = this.fsService;
        const fs = this.fs; // Keep fs for Wasm/Legacy if needed

        registry.register('ls', new LsCommand(fsService));
        registry.register('cd', new CdCommand(fsService));
        registry.register('pwd', new PwdCommand(fsService));
        registry.register('cat', new CatCommand(fsService));
        registry.register('grep', new GrepCommand(fsService));
        registry.register('mkdir', new MkdirCommand(fsService));
        registry.register('touch', new TouchCommand(fsService));
        registry.register('rm', new RmCommand(fsService));
        registry.register('cp', new CpCommand(fsService));
        registry.register('mv', new MvCommand(fsService));
        registry.register('echo', new EchoCommand(fsService));
        registry.register('head', new HeadCommand(fsService));
        registry.register('tail', new TailCommand(fsService));
        registry.register('wc', new WcCommand(fsService));
        registry.register('chmod', new ChmodCommand(fsService));
        registry.register('chown', new ChownCommand(fsService, this.identityService));
        registry.register('du', new DuCommand(fsService));
        registry.register('ln', new LnCommand(fsService));
        registry.register('df', new DfCommand(fsService));
        registry.register('find', new FindCommand(fsService));
        registry.register('sed', new SedCommand(fsService));
        registry.register('awk', new AwkCommand(fsService));
        registry.register('cut', new CutCommand(fsService));
        registry.register('tr', new TrCommand(fsService));
        registry.register('uniq', new UniqCommand(fsService));
        registry.register('sort', new SortCommand(fsService));
        registry.register('ed', new EdCommand(fsService));
        registry.register('cmp', new CmpCommand(fsService));
        registry.register('comm', new CommCommand(fsService));
        registry.register('diff', new DiffCommand(fsService));
        registry.register('paste', new PasteCommand(fsService));
        registry.register('tee', new TeeCommand(fsService));
        registry.register('cksum', new CksumCommand(fsService));
        registry.register('fold', new FoldCommand(fsService));
        registry.register('join', new JoinCommand(fsService));
        registry.register('nl', new NlCommand(fsService));
        registry.register('printf', new PrintfCommand(fsService));
        registry.register('split', new SplitCommand(fsService));
        registry.register('strings', new StringsCommand(fsService));
        registry.register('expand', new ExpandCommand(fsService));
        registry.register('unexpand', new UnexpandCommand(fsService));
        registry.register('tsort', new TsortCommand(fsService));
        registry.register('rmdir', new RmdirCommand(fsService));
        registry.register('link', new LinkCommand(fsService));
        registry.register('unlink', new UnlinkCommand(fsService));
        registry.register('readlink', new ReadlinkCommand(fsService));
        registry.register('realpath', new RealpathCommand(fsService));
        registry.register('sleep', new SleepCommand(fsService));
        registry.register('uname', new UnameCommand(fsService));
        registry.register('logname', new LognameCommand(this.identityService));
        registry.register('env', new EnvCommand(fsService));
        registry.register('cal', new CalCommand(fsService));
        registry.register('expr', new ExprCommand(fsService));
        registry.register('test', new TestCommand(fsService)); // Often aliased as [
        registry.register('[', new TestCommand(fsService));
        registry.register('od', new OdCommand(fsService));
        registry.register('uuencode', new UuencodeCommand(fsService));
        registry.register('uudecode', new UudecodeCommand(fsService));
        registry.register('who', new WhoCommand(fsService));
        registry.register('tty', new TtyCommand(fsService));
        registry.register('id', new IdCommand(this.identityService));
        registry.register('basename', new BasenameCommand(fsService));
        registry.register('dirname', new DirnameCommand(fsService));
        registry.register('pathchk', new PathchkCommand(fsService));
        registry.register('true', new TrueCommand());
        registry.register('false', new FalseCommand());
        // Time, Nohup, Nice need command provider
        registry.register('time', new TimeCommand(fsService, (name) => registry.get(name)));
        registry.register('nohup', new NohupCommand(fsService, (name) => registry.get(name)));
        registry.register('nice', new NiceCommand(fsService, (name) => registry.get(name)));
        registry.register('mkfifo', new MkfifoCommand(fsService));
        registry.register('file', new FileCommand(fsService));
        registry.register('timeout', new TimeoutCommand(fsService, (name) => registry.get(name)));
        registry.register('chgrp', new ChgrpCommand(fsService, this.identityService));
        registry.register('alias', new AliasCommand(fsService));
        registry.register('unalias', new UnaliasCommand(fsService));
        registry.register('type', new TypeCommand(fsService, registry));
        registry.register('pr', new PrCommand(fsService));
        registry.register('compress', new CompressCommand());
        registry.register('uncompress', new UncompressCommand());
        registry.register('zcat', new ZcatCommand(fsService));
        registry.register('asa', new AsaCommand(fsService));
        registry.register('dd', new DdCommand());
        registry.register('iconv', new IconvCommand(fsService));
        registry.register('jobs', new JobsCommand(fsService));
        registry.register('kill', new KillCommand(fsService));
        registry.register('ps', new PsCommand(fsService));
        registry.register('wait', new WaitCommand(fsService));
        registry.register('at', new AtCommand(fsService));
        registry.register('batch', new BatchCommand(fsService));
        registry.register('crontab', new CrontabCommand(fsService));
        registry.register('mailx', new MailxCommand(fsService));
        registry.register('mesg', new MesgCommand(fsService));
        registry.register('talk', new TalkCommand(fsService));
        registry.register('write', new WriteCommand(fsService));
        registry.register('bc', new BcCommand(fsService));
        registry.register('getconf', new GetconfCommand(fsService));
        registry.register('logger', new LoggerCommand(fsService));
        registry.register('man', new ManCommand(fsService));
        registry.register('tabs', new TabsCommand(fsService));
        registry.register('tput', new TputCommand(fsService));

        registry.register(':', new NullCommand());
        registry.register('exit', new ExitCommand());
        registry.register('sh', new ShCommand());
        registry.register('umask', new UmaskCommand());
        registry.register('times', new TimesCommand());
        registry.register('more', new MoreCommand(fsService));
        registry.register('strip', new StripCommand());
        registry.register('unset', new UnsetCommand());
        registry.register('export', new ExportCommand());
        registry.register('readonly', new ReadonlyCommand());
        registry.register('exec', new ExecCommand());
        registry.register('eval', new EvalCommand());
        registry.register('break', new BreakCommand());
        registry.register('continue', new ContinueCommand());
        registry.register('hash', new HashCommand());
        registry.register('trap', new TrapCommand());
        registry.register('getopts', new GetoptsCommand());
        registry.register('stty', new SttyCommand());
        registry.register('ulimit', new UlimitCommand());
        registry.register('fc', new FcCommand());
        registry.register('fg', new FgCommand());
        registry.register('bg', new BgCommand());
        registry.register('shift', new ShiftCommand());
        registry.register('read', new ReadCommand());
        registry.register('return', new ReturnCommand());
        registry.register('command', new CommandCommand((name) => registry.get(name)));
        registry.register('.', new DotCommand(fsService));
        registry.register('set', new SetCommand());
        registry.register('vi', new ViCommand());
        registry.register('ex', new ExCommand());
        registry.register('make', new MakeCommand());
        registry.register('ar', new ArCommand(fsService));
        registry.register('lex', new LexCommand());
        registry.register('yacc', new YaccCommand());
        registry.register('m4', new M4Command());
        registry.register('nm', new NmCommand());
        registry.register('patch', new PatchCommand());
        registry.register('pax', new PaxCommand());
        registry.register('lp', new LpCommand());
        registry.register('renice', new ReniceCommand());
        registry.register('admin', new AdminCommand());
        registry.register('c17', new C17Command(new WasmCompilerService(fsService), fsService));
        registry.register('cflow', new CflowCommand(fsService));
        registry.register('csplit', new CsplitCommand());
        registry.register('ctags', new CtagsCommand());
        registry.register('cxref', new CxrefCommand(fsService));
        registry.register('delta', new DeltaCommand());
        registry.register('fuser', new FuserCommand(fsService));
        registry.register('gencat', new GencatCommand(fsService));
        registry.register('get', new GetCommand());
        registry.register('gettext', new GettextCommand());
        registry.register('ipcrm', new IpcrmCommand());
        registry.register('ipcs', new IpcsCommand());
        registry.register('locale', new LocaleCommand());
        registry.register('localedef', new LocaledefCommand());
        registry.register('msgfmt', new MsgfmtCommand());
        registry.register('newgrp', new NewgrpCommand());
        registry.register('ngettext', new NgettextCommand());
        registry.register('prs', new PrsCommand());
        registry.register('rmdel', new RmdelCommand());
        registry.register('sact', new SactCommand());
        registry.register('sccs', new SccsCommand());
        registry.register('unget', new UngetCommand());
        registry.register('uucp', new UucpCommand());
        registry.register('uustat', new UustatCommand());
        registry.register('uux', new UuxCommand());
        registry.register('val', new ValCommand());
        registry.register('what', new WhatCommand());
        registry.register('xgettext', new XgettextCommand());
        registry.register('gzip', new GzipCommand());
        registry.register('gunzip', new GunzipCommand());
        registry.register('tar', new TarCommand());
        registry.register('cpio', new CpioCommand());
        registry.register('gcc', new GccCommand(new WasmCompilerService(fsService), fsService));

        // Factory-like registration for Xargs to avoid circular dependency in constructor
        registry.register('xargs', new XargsCommand(fsService, (name) => registry.get(name)));

        registry.register('whoami', new WhoamiCommand());
        registry.register('date', new DateCommand());
        registry.register('gui', new GuiCommand());
        registry.register('dispatch', new DispatchCommand());
        registry.register('scp', new ScpCommand());

        // Clear (Simple inline)
        registry.register('clear', {
            execute: (_args, _context, state) => ({
                output: '',
                newState: state,
                exitCode: 0,
                uiAction: 'CLEAR'
            })
        });
    }
}
